# Generated by Django 2.2.2 on 2019-08-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_blog',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='my_blog',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
